menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'POSC10: Principles of Governance and Politics'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/esthercalvo'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/esther-mary-calvo'}

contacts:
- {name: 'Esther Mary Calvo', title: 'PhD Candidate', department: 'Political Science', institution: 'Lund University',  institution_address: 'House: Eden, Allhelgona Kyrkogata 14', email: '<a href="mailto:esther.calvo@svet.lu.se">esther.calvo@svet.lu.se</a> | <br> <a href="mailto:esthermary.calvo@gmail.com">esthermary.calvo@gmail.com</a>'}
