menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

#courses:
#- {name: 'POSC10: Principles of Governance and Politics'}
#- {name: 'POSC141: Contemporary Political Ideologies'}
#- {name: 'SOSC2: Social, Political and Economic Thought'}

courses:
  university1:
    - {name: 'POSC10: Principles of Governance and Politics'}
    - {name: 'POSC141: Contemporary Political Ideologies'}
    - {name: 'SOSC2: Social, Political, and Economic Thought'}
    
  university2:
    - {name: 'Parties and Political Behavior (Fall 2022, Fall 2023)'}
    - {name: 'Comparative Politics (Spring 2023, Spring 2024)'}
    - {name: 'Research Methods in Development Studies (Fall 2023, Fall 2024)'}
    - {name: 'Political Science Methodology (Fall 2023)'}
    - {name: 'Swedish Politics (Fall 2024)'}
    - {name: 'Data Selection and Visualization in R (Spring 2025)'}
    
social:
- {icon: 'github', link: 'https://github.com/esthercalvo'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/esther-mary-calvo'}

contacts:
- {name: 'Esther Mary Calvo', title: 'PhD Candidate', department: 'Political Science', institution: 'Lund University',  institution_address: 'House: Eden, Allhelgona Kyrkogata 14', email: '<a href="mailto:esther.calvo@svet.lu.se">esther.calvo@svet.lu.se</a> | <a href="mailto:esthermary.calvo@gmail.com">esthermary.calvo@gmail.com</a>'}
